### ISSUE TITLE
GB CPU is not z80

### ISSUE THREAD

**Issue by ISSOtm** [ReyAnthony/sharp-z80-LR35902#7]
Hi!
Just wanted to let you know the repo and site's titles are wrong: the GB CPU is simply called the Sharp LR35902.
Calling it a z80 is wrong, and very misleading, since a lot of people believe the LR35902 is actually a custom z80.
Its fan nickname is the GBz80, but that's also fairly misleading.

**Comment by ReyAnthony** [comment]
Osef

Le sam. 15 déc. 2018 à 21:30, Eldred Habert <notifications@github.com> a
écrit :

**Comment by ReyAnthony** [comment]
Hi,

Thanks for the insight, I might change it when I'll have some time not to spread misinformation

But to be honest, I frankly don't really care
